apiVersion: apps/v1
kind: Deployment
metadata:
  name: harj-deployment
  labels:
    app: harj-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harj-nginx
  template:
    metadata:
      labels:
        app: harj-nginx
    spec:
      containers:
      - name: harj-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80